### ISSUE TITLE
State of the field: comparison to SDToolbox

### ISSUE THREAD

**Issue by cartemic** [corykinney/RGFROSH#14]
> State of the field: Do the authors describe how this software compares to other commonly-used packages?

Are you familiar with [SDToolbox](https://shepherd.caltech.edu/EDL/PublicResources/sdt/)? In my experience that is a commonly used package for detonation research, and it provides some similar functionalities (e.g. frozen shock calculations).  I think it may be worth mentioning how `rgfrosh` compares. As an example, `rgfrosh` allows the user to use coolprop as well as cantera.

**Comment by corykinney** [comment]
@cartemic I was not familiar with SDToolbox, I assume it's more used in the detonation community as I haven't heard it discussed in the shock tube community. It looks pretty extensive, and from what I can tell it could be used with an appropriate Cantera real gas mechanism to get results consistent with `rgfrosh`. For review purposes, are you wanting me to add SDToolbox to state of the field for the paper, specifically?

Based on some non-exhaustive reading of SDToolbox's documentation. The main advantages for `rgfrosh` for shock tube use would be:
- Compatibility: as you mentioned, `rgfrosh` is not limited to only using Cantera, but CoolProp (and by extension REFPROP), and any other tool the user wants with a simple interface definition.
- Convenience: it's tailor made for shock tube experiments so it automatically makes available all state 2 and state 5 information for reflected shocks instead of having to make multiple calls to SDToolbox's API and perform calculations for the remaining information. `rgfrosh` also has the dedicated functions for solving the inverse problem to set up experiments. 

Some other code differences that *might* be noteworthy:
- `rgfrosh` solves Jacobians analytically as opposed to just the finite difference approach, which might help with performance for complex equations of state as it might reduce the number of expensive evaluations, but I haven't investigated this myself to see whether `rgfrosh` is faster (or slower) than SDToolbox. This is an interesting idea though, as I'm inclined to add a finite difference fallback in the case that the additional properties aren't available, which would further improve the compatibility `rgfrosh` for potentially incomplete EOS implementations.
- Based on [Section 8.2](https://shepherd.caltech.edu/EDL/PublicResources/sdt/doc/ShockDetonation/ShockDetonation.pdf#section.8.2) of their documentation, it seems they also have some hardcoded initial guesses, whereas `rgfrosh` starts from ideal shock solutions, which might improve solver stability and convergence speed, but, again, I haven't investigated that as it will be highly dependent on the initial conditions.

A side note: `rgfrosh` can be `pip` installed, which is great for easier installation and integration into other projects CI/CD, and is generally more available since it has an actual repository that pull requests and issues can be submitted to, with organized web documentation. After seeing SDToolbox's capabilities, I really wish there was an official GitHub repository (if there is, I can't find one) so that I could more readily use and interact with the project!

**Comment by cartemic** [comment]
Thank you for adding that! I really like how flexible `rgfrosh` is with the thermodynamic interface. It is very convenient to be able to pip install, and the use of `ThermoInterface` keeps the dependency list minimal. I agree about SDToolbox; it is a very useful package on which a lot of my work has depended, and I would love to see it on GitHub as well.
